from __future__ import annotations

from mf_log_analyzer_v2.core.models import Calibration, ChannelDefinition, VehicleProfile


def channel(
    channel_id: str,
    display_en: str,
    display_ko: str,
    source_columns: tuple[str, ...],
    unit: str,
    group: str,
    color: str,
    calibration: Calibration | None = None,
    required: bool = False,
) -> ChannelDefinition:
    return ChannelDefinition(
        channel_id=channel_id,
        display_name={"en": display_en, "ko": display_ko},
        source_columns=source_columns,
        unit=unit,
        group=group,  # type: ignore[arg-type]
        color=color,
        calibration=calibration or Calibration(),
        required=required,
    )


def mf_default_profile() -> VehicleProfile:
    adxl_correction = Calibration(scale=0.125)
    channels = {
        "Timestamp": channel(
            "Timestamp",
            "Timestamp",
            "시간",
            ("Timestamp",),
            "s",
            "Time",
            "#9ca3af",
            required=True,
        ),
        "RPM": channel("RPM", "RPM", "RPM", ("RPM",), "rpm", "Engine", "#d55e00"),
        "TPS_PERCENT": channel(
            "TPS_PERCENT",
            "Throttle Position",
            "스로틀 포지션",
            ("TPS_percent",),
            "%",
            "DriverInput",
            "#e69f00",
        ),
        "EOT_IN": channel(
            "EOT_IN",
            "Engine Oil Temp In",
            "엔진오일 온도 IN",
            ("EOT_IN", "OilTemp_C"),
            "degC",
            "CoolingOil",
            "#f59e0b",
        ),
        "EOT_OUT": channel(
            "EOT_OUT",
            "Engine Oil Temp Out",
            "엔진오일 온도 OUT",
            ("EOT_OUT",),
            "degC",
            "CoolingOil",
            "#d97706",
        ),
        "OilPressure_bar": channel(
            "OilPressure_bar",
            "Oil Pressure",
            "오일 압력",
            ("OilPressure_bar",),
            "bar",
            "CoolingOil",
            "#009e73",
        ),
        "Batt_V": channel(
            "Batt_V",
            "Battery Voltage",
            "배터리 전압",
            ("Batt_V",),
            "V",
            "Electrical",
            "#56b4e9",
        ),
        "AX_CORRECTED_G": channel(
            "AX_CORRECTED_G",
            "Corrected Longitudinal G",
            "보정 종가속도",
            ("ax_g",),
            "g",
            "IMU",
            "#0072b2",
            adxl_correction,
        ),
        "AY_CORRECTED_G": channel(
            "AY_CORRECTED_G",
            "Corrected Lateral G",
            "보정 횡가속도",
            ("ay_g",),
            "g",
            "IMU",
            "#cc79a7",
            adxl_correction,
        ),
        "AZ_CORRECTED_G": channel(
            "AZ_CORRECTED_G",
            "Corrected Vertical G",
            "보정 수직가속도",
            ("az_g",),
            "g",
            "IMU",
            "#8b5cf6",
            adxl_correction,
        ),
        "GPS_Speed_KPH": channel(
            "GPS_Speed_KPH",
            "GPS Speed",
            "GPS 속도",
            ("GPS_Speed_KPH",),
            "km/h",
            "GPS",
            "#22c55e",
        ),
        "Latitude": channel("Latitude", "Latitude", "위도", ("Latitude",), "deg", "GPS", "#60a5fa"),
        "Longitude": channel("Longitude", "Longitude", "경도", ("Longitude",), "deg", "GPS", "#34d399"),
        "DBW_TARGET_PERCENT": channel(
            "DBW_TARGET_PERCENT",
            "DBW Target",
            "DBW 목표",
            ("DBW_Target_percent",),
            "%",
            "DBW",
            "#f97316",
        ),
        "DBW_ACTUAL_PERCENT": channel(
            "DBW_ACTUAL_PERCENT",
            "DBW Actual",
            "DBW 실제",
            ("DBW_Pos_percent",),
            "%",
            "DBW",
            "#3b82f6",
        ),
        "SUSP_FL_MM": channel(
            "SUSP_FL_MM",
            "Suspension FL",
            "서스펜션 FL",
            ("Susp_FL_mm",),
            "mm",
            "Suspension",
            "#f59e0b",
        ),
        "SUSP_FR_MM": channel(
            "SUSP_FR_MM",
            "Suspension FR",
            "서스펜션 FR",
            ("Susp_FR_mm",),
            "mm",
            "Suspension",
            "#ef4444",
        ),
        "SUSP_RL_MM": channel(
            "SUSP_RL_MM",
            "Suspension RL",
            "서스펜션 RL",
            ("Susp_RL_mm",),
            "mm",
            "Suspension",
            "#10b981",
        ),
        "SUSP_RR_MM": channel(
            "SUSP_RR_MM",
            "Suspension RR",
            "서스펜션 RR",
            ("Susp_RR_mm",),
            "mm",
            "Suspension",
            "#6366f1",
        ),
    }
    return VehicleProfile(profile_id="mf-default", name="MF Default Vehicle", channels=channels)
